### ISSUE TITLE
Which version of ADI is used here? 

### ISSUE THREAD

**Issue by RiSi95** [AyushDoshi/geocode-adi#1]
Hi, I'm just wondering which version of ADI from the Neighborhood Atlas is being used here. I would assume it is the 2015 or 2018 (v3.0) ADI given the code publication year? If I wanted to manually update the library to use 2020 ADI, would I need to do anything special other than renaming the columns to match your .feather file? Thank you!

**Comment by AyushDoshi** [comment]
Sorry for not keeping up with the code base and ADI updates. I hope you got it to work with the more updated versions when you needed it and it wasn't too much trouble. I have updated the package to include the 3 years/versions of data currently available (2021, 2020, and 2015).
